/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cps240.TermProject;

public class Launcher {

    public static void main(String[] args) {
      Main.main(args);
    }
}
