name: Build
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - run: ./gradlew test jar --no-daemon
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: build/libs/cps240-term-project.jar
